### ISSUE TITLE
FiveM Menu

### ISSUE THREAD

**Issue by midoom** [ldlac/La_LifeRP#1]
Bonsoir et merci de votre release, je viens de lancer le server et tout config pour la base SQL
mais j'ai une erreur avec le script FiveM Menu. Je vous poste l'erreur en image
[http://imgur.com/a/LYKPf](http://imgur.com/a/LYKPf)

**Comment by PichotM** [comment]
Pour corriger cette erreur tu vas dans  fivemenu/client_data.lua et tout en bas tu supprimes les 3 dernières lignes "informateurs"

**Comment by PichotM** [comment]
et aussi les tables dans drogue_serveur

**Comment by midoom** [comment]
Y'a pu d'erreur dans la console mais le menu ne s'ouvre toujours pas :(

**Comment by NacimYamm** [comment]
Bonjour, il faut supprimer quoi dans Drogue_server ? Merci

**Comment by ShakirDarwish** [comment]
Bonjours a tous nous somme en trian de régler le probleme à l'instant même

**Comment by ShakirDarwish** [comment]
Voila c'est corriger
