### ISSUE TITLE
MASSE ERROR

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#100]
Bonjour, 
Voici les error en masse dans les logs :
https://image.noelshack.com/fichiers/2017/23/5/1497009569-error.png

**Comment by sim2511** [comment]
Ça serait bien que tu poses toutes tes questions sur le discord, plutôt que de flood le github 50 fois par jours.

**Comment by Julian51100** [comment]
bah j'aime pas discord c'est pas top puis sur le discord perso répond :(

**Comment by Julian51100** [comment]
corriger ?
