### ISSUE TITLE
Minage automatique

### ISSUE THREAD

**Issue by RayZennn** [ldlac/La_LifeRP#103]
Salut J'aimerais savoir comment mettre le minage automatique sur le job mineur [Script : mine_jobs.lua]

**Comment by rvwarrior** [comment]
tu enlèves le if et le end correspondant

**Comment by RayZennn** [comment]
quel ligne :D ?

**Comment by rvwarrior** [comment]
ça dépend, là où tu veux que ça le fasse, la récolte, le traitement et les ventes sont disposés en blocs, il sont assez faciles à repérer

**Comment by RayZennn** [comment]
if IsControlJustPressed(1,38) then

C'est ça non ?

**Comment by rvwarrior** [comment]
yep

**Comment by RayZennn** [comment]
ok je vais essayer la :D, merci pour l'aide tes les meilleurs

**Comment by Quick24** [comment]
Bonjour, Jaimerais cree un job pecheur mais j'aimerais avoir de l'aide vous pourriez m'aider rvwarrior??

**Comment by RayZennn** [comment]
Quand je modifie 
if IsControlJustPressed(1,38) then en -- if IsControlJustPressed(1,38) then

le job disparait de la map

**Comment by rvwarrior** [comment]
Ray, as tu commenté le end qui va avec ?

**Comment by RayZennn** [comment]
local distance = GetDistanceBetweenCoords(playerPos.x, playerPos.y, playerPos.z, Position.Recolet.x, Position.Recolet.y, Position.Recolet.z, true)
    if not IsInVehicle() then
      if distance < Position.Recolet.distance then
        ShowInfo('~b~Appuyez sur ~g~E~b~ pour miner', 0)
        if IsControlJustPressed(1, 38) then
          TriggerServerEvent("poleemploi:getjobs")
          Wait(100)
          if myjob == 4 then
            if carJob == true then
              TriggerEvent("player:getQuantity", 23)
              roche = qte
              TriggerEvent("player:getQuantity", 17)
              cuivre = qte
              TriggerEvent("player:getQuantity", 18)
              fer = qte
              TriggerEvent("player:getQuantity", 19)
              diams = qte
              -- TriggerEvent("player:getQuantity", 4, function(data)
              --     weedcount = data.count
              -- end)
              local chance_mat = math.random(chance,1000)
              Wait(100)
              Citizen.Wait(1)
              if (roche+cuivre+fer+diams) < 30 and chance_mat <=500  then
                ShowMsgtime.msg = 'Minage en cour'
                ShowMsgtime.time = 250
                TriggerEvent("vmenu:anim" ,"pickup_object", "pickup_low")
                Wait(2500)
                ShowMsgtime.msg = '~g~ + 1 ~b~Roche'
                ShowMsgtime.time = 150
                TriggerEvent("player:receiveItem", 23, 1)
                chance = chance + 1

              elseif (roche+cuivre+fer+diams) < 30 and chance_mat <=800  then
                ShowMsgtime.msg = 'Minage en cour'
                ShowMsgtime.time = 250
                TriggerEvent("vmenu:anim" ,"pickup_object", "pickup_low")
                Wait(2500)
                ShowMsgtime.msg = '~g~ + 1 ~b~cuivre'
                ShowMsgtime.time = 150
                TriggerEvent("player:receiveItem", 17, 1)
                chance = chance + 1

              elseif (roche+cuivre+fer+diams) < 30 and chance_mat <= 980 then
                ShowMsgtime.msg = 'Minage en cour'
                ShowMsgtime.time = 250
                TriggerEvent("vmenu:anim" ,"pickup_object", "pickup_low")
                Wait(2500)
                ShowMsgtime.msg = '~g~ + 1 ~b~fer'
                ShowMsgtime.time = 150
                TriggerEvent("player:receiveItem", 18, 1)
                chance = chance + 1

              elseif (roche+cuivre+fer+diams) < 30 and chance_mat <= 1000  then
                ShowMsgtime.msg = 'Minage en cour'
                ShowMsgtime.time = 250
                TriggerEvent("vmenu:anim" ,"pickup_object", "pickup_low")
                Wait(2500)
                ShowMsgtime.msg = '~g~ + 1 ~b~Diamant'
                ShowMsgtime.time = 150
                TriggerEvent("player:receiveItem", 19, 1)
                chance = 1

              else
                ShowMsgtime.msg = '~r~ Inventaire plein, allez au traitement !'
                ShowMsgtime.time = 150
              end
            else
              ShowMsgtime.msg = '~r~ Vous devez avoir été dans le bon véhicule dans les 5 dernières minutes !'
              ShowMsgtime.time = 150
            end
          else
            ShowMsgtime.msg = '~r~ Vous devez être mineur !'
            ShowMsgtime.time = 150
          end
        end
      end
    end

**Comment by rvwarrior** [comment]
Quick, envoie moi un message par Discord

**Comment by RayZennn** [comment]
ok

**Comment by rvwarrior** [comment]
Ray, question juste comme ça, connais tu un langage de programmation ?

**Comment by RayZennn** [comment]
yep

**Comment by RayZennn** [comment]
Lua/C#/C++

**Comment by ldlac** [comment]
Sera implanté prochainement

**Comment by smixiop** [comment]
j ai deja réglé ce prob tu rajoute une 
while
