### ISSUE TITLE
Removal for es_freeroam

### ISSUE THREAD

**Issue by ghermans** [ldlac/La_LifeRP#104]
We hereby request you to remove **es_freeroam** from your repository since you are violating our license & disclaimer.    
This is hard work we have done in good faith, meaning we aren't paid for any of the code we create for es_freeroam.   
We spend a lot of time debugging the code, maintaining it, and testing it so other people can enjoy this gamemode.   
While we release the source code so people can modify es_freeoam to meet their needs,   
We don’t like it when people don’t credit the original creators.   
You can contact us in our Discord server if you have any questions. 

### You violated our terms as seen here:

![disclaimerknipsel2](https://user-images.githubusercontent.com/1594411/26983862-7ff3e7cc-4d3d-11e7-8852-7a245d870df6.PNG)

## These files have been modified/removed
- the License file has been removed
- the readme file has been removed
- the contributing file has been removed
- the changelog file has been removed
- you copy/pasted our disclaimer inside your [license](https://github.com/ldlac/La_LifeRP/blob/master/LICENSE.md) file

If **es_freeroam** isn't removed within 24 hours we will send a DCMA request to Github and remove this repository. 

- The FS Team

**Comment by sim2511** [comment]
Wow what a mentality, you have a insane good team of dev working for open source, and you have other one trying to destroy what they are doing.

**Comment by Kyominii** [comment]
Have you read the message first ?
@ghermans said that there is no credit for es_freeroam. So it's normal to ask to have some credits for this hard work

**Comment by ldlac** [comment]
Discussion in progress. This is just a misunderstanding.

**Comment by ldlac** [comment]
Deleted during discussion. Sadly.
Current master is broken at the moment. Will need new replacement.
Closing the issue. Project on the ice during this phase.
