### ISSUE TITLE
Impossible d'appeler une ambulance

### ISSUE THREAD

**Issue by Draxprodd** [ldlac/La_LifeRP#108]
Bonjour,

Soucis avec le coma, une fois dans le coma on ne peux pas faire "E" pour appeler une ambulance, en faisant "E" on respawn automatiquement, et une fois avoir respawn en faisant "E" on à la notification "Appuyez sur E pour appeler une ambulance".. 

La notification arrive tard, très tard même, une fois respawn on a la notif, alors qu'une fois dans le coma on ne l'a pas.

Je pense qu'il faudrait revoir tout le système étant donné que la notification arrive trop tard et quand on fait "E" on respawn directement.

**Comment by loko06320** [comment]
Meme problème a un moment j'ai limpression depuis le fix ambulance de la master , remplace le  dossier ambulance par celui de la version stable, ca a marché chez moi

**Comment by buddyqc** [comment]
Utilise la version stable au pire?

**Comment by ldlac** [comment]
Emergency n'est pas encore stable.
Et stable devrait être mise à jour bientôt.
Et Emergency fonctionne super bien de mon côté, assurez vous d'avoir des ambulanciers en service (jobid = 13)

**Comment by buddyqc** [comment]
Sur stable sa fonctionne bien moi
