### ISSUE TITLE
Téléphone

### ISSUE THREAD

**Issue by OrionSosa** [ldlac/La_LifeRP#109]
Je cherche depuis 1h pour réactiver le téléphone au volant,
de l'aide svp

**Comment by buddyqc** [comment]
Moi quand jutilise le telephone au volant il tombe debout le perso et je me plante solide a 140km/h lolll comment fix ce genre de probleme?

**Comment by Flookyy** [comment]
n ouvre pas ton tell au volant  c est dangereux

**Comment by ldlac** [comment]
@buddyqc C'est fix depuis quelques patchs

**Comment by buddyqc** [comment]
Sur stable ou master?

**Comment by ldlac** [comment]
Master

**Comment by buddyqc** [comment]
Jutilise la stable

**Comment by buddyqc** [comment]
Mais je vais switch sur la master en 2 version jaimerais mimpliquer un peu je veux faire un serveur a montreal et je garderait vos credits

**Comment by buddyqc** [comment]
Je pense planifier un lspd integrer sur le serveur pour dossier criminel etc
