### ISSUE TITLE
Nom a la connection 

### ISSUE THREAD

**Issue by TonTonSheitan** [ldlac/La_LifeRP#112]
Bonjour, j'utilise un script pour une notification quand un joueur se connecte et déconnecte, mais quand le joueur ce co et deco sa me donne sont pseudo steam et justement je voudrais que sa affiche le nom prénom qui mettent au début lors de la 1er connexion. Si quelqu’un aurait la solution sa serait sympa :) 

Merci 

Script:

AddEventHandler('playerConnecting', function()
	TriggerClientEvent('showNotify', -1, "~g~"..GetPlayerName(source).." ~w~ s'est connecté")
end)

**Comment by ShakirDarwish** [comment]
Faudrait changer le GetPlayerName(source), par le nom et le prénom dans la db, la section Issues du GitHub est pour les bug et non pour les questions

**Comment by TonTonSheitan** [comment]
ah ok désoler
