### ISSUE TITLE
Duplications de job

### ISSUE THREAD

**Issue by NikoDEK** [ldlac/La_LifeRP#113]
Bonjour, je suis de très prêt votre projet qui est vraiment magnifique mit connaissant un peu j'ai essayer de travail le job mineur pour le dupliquer a d'autre job , Pécheur par exemple mais après plusieurs recherche modifications de certain fichier.lua pour l'ajout des items des animations ect rien n'y fait le menu ne s'affiche plus ou alors sa ne récolte pas --' 
Ses pour cela que je me permet de vous demandez si il serait possible de m'indiquer les fichiers a modifier pour tester la duplication de job et pourquoi vous les proposer par la suite dans les requests merci d'avance et bonne continuation pour votre beau projet

**Comment by ldlac** [comment]
Tu sembles avoir oublié des , ou des " ou des { }. Fais gaffe lorsque tu modifies, en principe ça devrait fonctionner.

**Comment by buddyqc** [comment]
Oublie pas le ressource_.lua

**Comment by NikoDEK** [comment]
ah d'accord oui oui je sauvegarde avant chaque modife ect je vais regarder sa de plus pres :) merci a vous pour votre reponse rapide
