### ISSUE TITLE
Crocheter la serrure

### ISSUE THREAD

**Issue by mic75013** [ldlac/La_LifeRP#114]
Hello

Quand je tente de crocheter une serrure, mon jeu crash avec cette erreur

http://www.hostingpics.net/viewer.php?id=570098bugcroch.png

Je suis sur la dernière version Master branche ( 10/06 - 21h ) 

Bravo pour votre taff, vive LaLife !

**Comment by ldlac** [comment]
Devrait être fix avec l'update du Wrapper
