### ISSUE TITLE
Question linux

### ISSUE THREAD

**Issue by SxProject** [ldlac/La_LifeRP#115]
bonjour j'ai mis en place votre archive (la version stable) sous Debian et au lancement tout fonctionne mais je n'ai pas la console de chargement des sources, juste des petit points.
et je souhaiterais si possible savoir comment augmenter les places dans le garage qui est de 5 en ce moment.
merci beaucoup pour votre travail et surtout de nous le partager.

**Comment by MRLEGENDS03** [comment]
Bonjour, avec quel logiciel prend tu la main à distance ?
à tu un screen ?

**Comment by SxProject** [comment]
bonjour je prend la main avec putty

**Comment by SxProject** [comment]
![capture](https://user-images.githubusercontent.com/29329625/27009686-b680fd04-4e94-11e7-99ee-e3ca2b072149.JPG)

**Comment by MRLEGENDS03** [comment]
à tu fait un [chmod +x run.sh]  ?

**Comment by SxProject** [comment]
oui

**Comment by MRLEGENDS03** [comment]
tu as la version stable ou master de la life ?

**Comment by SxProject** [comment]
la version stable

**Comment by MRLEGENDS03** [comment]
sous quelle version de mono est-tu ?

**Comment by SxProject** [comment]
4.6

**Comment by MRLEGENDS03** [comment]
tu as essayer avec la 4.8 ?

**Comment by SxProject** [comment]
non

**Comment by SxProject** [comment]
je vais tester

**Comment by MRLEGENDS03** [comment]
ok

**Comment by ldlac** [comment]
Je vais fermé l'issue parce qu'en principe tout fonctionne sur linux. Merci aux gens qui lui apporte de l'aide :)!

**Comment by SxProject** [comment]
pas de souci et merci pour tous.
