### ISSUE TITLE
Armes quand on meurt

### ISSUE THREAD

**Issue by Alkatrazz** [ldlac/La_LifeRP#120]
J'ai fait la dernière update qui normalement arrangeait ce soucis mais même probleme quand on meurt, qu'on deco reco on retrouve l'arme qu'on avait acheté

**Comment by SirSmog1** [comment]
vous tentez de faire que la mort supprime les armes au shops ?!

**Comment by Alkatrazz** [comment]
Non, Draziak comprendra

**Comment by dante047** [comment]
Ouai pareille on recup les armes après une déco.

**Comment by SirSmog1** [comment]
sa pourrais etre pas pire qu'il sois redonner seulement au reboot serveur et non au deco/reco

**Comment by ldlac** [comment]
Fixed
