### ISSUE TITLE
Création de nouveau items

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#121]
Bonjours
je tente présentement de crée de nouveau item pour manger et boir

voici ma BDD actuel
http://imgur.com/a/D0g8g

et ici ma config inventory.lua
http://imgur.com/a/TuGbm

le problème : 
le joueur mange n'importe quel items qui devrais ce boir et remonter sa barre bleu d'hydratation
mais les items remonte la barre verte de nourriture .....
donc possible de crée des items a manger mais non a boire

Merci d'avance

**Comment by ldlac** [comment]
Je crois que tu utilises foodhud avec les types dans ta bdd? Je n'ai pas encore implanté mon propre système de type dans la bdd de LaLife haha... Ça va venir. C'est géré autrement en ce moment. Avec l'ID de l'item je crois. Il n'y a que l'ID 1 qui donne de l'eau. C'est visible inventory_client.lua si je me rappelle bien.

**Comment by SirSmog1** [comment]
dac merci de votre réponse je vais attendre votre système custom ;)

**Comment by gallicgames** [comment]
Sinon tu a la possibilité effectivement de créer tes items par toi meme a l'aide de "inventory.lua" dans  ressources>[citizenz]>Fivemenu>Inventory.lua

Une fois la ligne ajoutée tel que : 
    {name="TONOBJET (ex: donuts)", id=1, price=3, value=30},  
   price= prix (tu ajuste)
   value c'est le nombre qu'il ajoute a ta barre de faim ou de soif /100

Tu va dans ta base de donné dans les items et tu t'assure d'ajouter le meme item avec le bon id (il doit être unique évidement)

Éclate toi

**Comment by SirSmog1** [comment]
gallicgames a tu pris la peine de ragarde les capture d'ecrant qui montre le
inventory.lua de mon serveur
et la BDD =='

en tout les cas jai modifier le tout en attente dune version refaite de chez LaLifeTeam

merci quand même de vouloir aider ;)

**Comment by ldlac** [comment]
Vu que le problème est personnel, je vais close, vous pouvez continuer la discussion.
