### ISSUE TITLE
Création de couleur de cheveux

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#122]
Bonjours

j'aimerais savoir si les couleur de cheveux son prévue dans les MAJs a venir ou
nous devons les configurer nous même  ....

si la configuration est requis de la part des admin serveur
j'aimerais si possible avoir des explications sur la méthode a utiliser pour en rajouter

pour le moment nous avons que 4 couleur je croix qui son 
noir noir noir et noir pale xD

Merci d'avance

**Comment by Alkatrazz** [comment]
C'est un bug, faut être patient

**Comment by SirSmog1** [comment]
dac merci de votre réponse rapide ;)
