### ISSUE TITLE
Création de nouveau User

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#123]
Bonjours

j'ai certain joueur qui arrive a outrepasser le Ccreation d'arriver pour les nouveaux joueurs
ci qui arrive a ce moment il se crée un User nom Citizen Prenom Citizen

http://imgur.com/a/sAMLB

cela cause des problème quand 2 joueur nommé Citizen son connecter en même temps

serait il possible d'ajouter une option qui détecte les Citizen User 
pour les kicks du serveur et leur relancer le Ccreation darriver quand il reconnecte ?!

Merci d'avance

**Comment by buddyqc** [comment]
Tu peux la cree

**Comment by buddyqc** [comment]
Je vais verifier cela de mon bord ce soir.

**Comment by buddyqc** [comment]
Ca prend une query pour verifier les user apres 15 minute ex. Qui ont ce user les kick et remplacer isfirstconnection par 0 ca va leur redemander le ccreation

**Comment by SirSmog1** [comment]
oui sa serais parfait car pour le moment on le fait manuellement et les joueurs sans se rendre compte continue a jouer et de notre coter on supprime les profils xD

merci pour ta réponse rapide ;)

**Comment by buddyqc** [comment]
Ajoute moi sur steam finestlyker590 je va verifier avec toi

**Comment by SirSmog1** [comment]
ton steam ne sort pas

**Comment by SirSmog1** [comment]
rejoins moi au ts.quebeccrew.com

**Comment by buddyqc** [comment]
Je suis dessu

**Comment by Alkatrazz** [comment]
ou sinon /changename prenom nom

**Comment by SirSmog1** [comment]
cette commande fonctionne que pour les Citizen name User ?! ou tout les joueurs peuve la faire  ?!

**Comment by Alkatrazz** [comment]
Que pour les gens qui ont Citizen citizen

**Comment by SirSmog1** [comment]
tes tu srx .... xDD sa prend vraiment un docu des commandes x)
entk merci beaucoup Alkatrazz bin gentils a toi ;)
pis merci aussi a Buddy

**Comment by ldlac** [comment]
Ouais en ce moment les commandes sont dans le code, et dans ma tête, mais comme les deux sont difficilement lisibles/accessibles, ça cause certains soucis.

**Comment by SirSmog1** [comment]
il son ou dans le code ?! je vais verif rapido
je me demandais aussi ya til une cmd pour viewname les IDs de joueur ?
