### ISSUE TITLE
Problème serveur

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#124]
Bonjour,
Je poste cette ISSUES car j'ai un soucis sur mon serveur ...
Ya peu de temps j'avais une machine chez FIRST HEBERG avec 4 go de ram et 2 vcore
et j'ai changer pour aller chez OVH car les joueurs disparaissait dans la partit sauf que le problème et toujours présente en pleine game les joueurs jl'es vois plus ..
D'ou ceci pourrais venir ?

**Comment by Julian51100** [comment]
Je tiens à dire que j'ai juste relier la base de donnée au serveur mais j'ai pas configurer les point de dealer illégaux encore mais je pense que ceci ne viens pas de la ...

**Comment by SirSmog1** [comment]
je suis chez OVH et je tourne 2 serveur sur la même machine et nous n'avons pas de soucis d'instance
provenant du framework LaLifeRp

avez vous installer d'autres scripts sur votre serveur ?!
ou pack stream supplémentaire ?!
le firewall antiddos OVH est il activer ET configurer ?!
les port de votre machine sont il correctement configurer ?!

**Comment by Julian51100** [comment]
aucun autre script (j'utilise la ressource master pas la stable car elle marche pas,
j'au pas activer le firewall :( 
non j'ai juste desactiver le parefeu et basta 
oui j'ai fais aussi une autre issue :(

**Comment by Julian51100** [comment]
tu peux venir ts ou un truc comle sa ?

**Comment by SirSmog1** [comment]
quel forfait a tu louer cher OVH ?

**Comment by SirSmog1** [comment]
ya le discord du team de LaLifeRp qui dois être dispo ;)
mais je doute que ton problème d'instance sois acause de leur framework

**Comment by MagnanQC** [comment]
C'est un probleme de streamer, de connexion entre le client et le serveur.
as tu modifier le wrapper ?

**Comment by Julian51100** [comment]
SirSmog1:
D'accord bah j'suis sur ton ts la ;)
MagnanQC:
Non dutout

**Comment by Julian51100** [comment]
Fichier server ?

**Comment by Julian51100** [comment]
FERMETURE DU PARE FEU,
OUVERTURE DES PORTS SERVEUR DE BASE (30120)
OUVERTURE DES PORTS DE HEIDISQL (3306)
INSTALATION DE TEAMVIEWER SUR LE SERVEUR

**Comment by ldlac** [comment]
Fermeture de cet issue, vu que tu en as un autre ouvert
