### ISSUE TITLE
ERROR DE MASSE

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#125]
Bonjour, Voici les erreurs de masse que j'ai:
https://image.noelshack.com/fichiers/2017/24/2/1497386634-error.png
https://image.noelshack.com/fichiers/2017/24/2/1497386637-error1.png
https://image.noelshack.com/fichiers/2017/24/2/1497386639-error2.png
https://image.noelshack.com/fichiers/2017/24/2/1497386640-error3.png

**Comment by Alkatrazz** [comment]
J'ai vu des trucs qu'il y a pas dans les sources de lalife donc si tu as modifié toi même les scripts tu devrais pouvoir les relire pour voir se qu'il ne va pas :)

**Comment by Julian51100** [comment]
J'ai rien touché ...

**Comment by Alkatrazz** [comment]
Si tu n'as rien touché tu as au moins ajouté des scripts, en tout cas je n'ai jamais vu ce genre d'erreur sans avoir rien touché

**Comment by SirSmog1** [comment]
sv_emergency ses le script de médecin
https://forum.fivem.net/t/release-job-save-people-be-a-hero-paramedic-emergency-coma-ko/19773

**Comment by SirSmog1** [comment]
dois avoir un soucis a mettre les ambulancier en service 0 
donc peut être un problème au niveau de ta base de donné ......

**Comment by Julian51100** [comment]
Bizzard ...

**Comment by Julian51100** [comment]
https://image.noelshack.com/fichiers/2017/24/3/1497449473-screenshot.png 

ENCORE PAREIL APRES AVOUE RIEN TOUCHER ENCORE UNE FOIS !

**Comment by sim2511** [comment]
est ce que vous pourriez échanger en privé, je suis abonné aux notifications de ce github, et c'est tout simplement du spam, si vous avez des questions allez sur le discord, MERCI

**Comment by buddyqc** [comment]
Ce nest pas du spam?

**Comment by buddyqc** [comment]
As tu debloquer toutes les fichiers .dll dans essential et async? Si je me rappel bien ca peux venir de la

**Comment by Julian51100** [comment]
yep ;)

**Comment by MagnanQC** [comment]
Donne moi ton nom discord, ma aller voir sa avec toi.

**Comment by MagnanQC** [comment]
J'ai pas TeamSpeak, et je suis pas intéresser de l'avoir. 
Désolé.

**Comment by Julian51100** [comment]
Mon nom c'est sois dqsd     ou  Julian.F

**Comment by buddyqc** [comment]
tu n'a rien modifié mais tu as ajouter le mods emergency en dehors du frame La Life ?

**Comment by Julian51100** [comment]
nn

**Comment by SirSmog1** [comment]
le script Emergency est dans le framework de LaLife par défaut
il est dans [Jobs]/emergency

**Comment by ldlac** [comment]
Essaie de te mettre à jour avec la plus récente version, ce genre d'erreur est sensé être réglé depuis un moment. Tu as toujours les erreurs?

**Comment by Julian51100** [comment]
Bonjour, 
j'ai des error dans essencialmode de login ligne 39:3

**Comment by SirSmog1** [comment]
sa dois venir de la BDD qui est mal regler et le script demergency ne dois pas arriver a sortir ou entree en service les medics ....
