### ISSUE TITLE
[BUG] Garage Police + Police

### ISSUE THREAD

**Issue by DayField** [ldlac/La_LifeRP#126]
On ne peut pas retirer de véhicule depuis le garage police. De plus la prise de service en police n update pas le métier (et le menu police est dispo même en hors service) . Les deux derniers bugs restent mineurs bien sûr

**Comment by SirSmog1** [comment]
de mon coter tout est OK

Prise de service donne le bon métier et bon salaire
et le garage police fonctionne biens

mais il est vrais que le menu police reste activer sans avoir le service en fonction ... meme probleme pour moi

**Comment by DayField** [comment]
Tu es sur version stable ou master ?

**Comment by SirSmog1** [comment]
master presentement

**Comment by buddyqc** [comment]
la version stable n'est plus recommandé à ce que jai pu voir de Idlac sur plusieurs conversations.
Je vous recommande donc la version Master la version stable va être remplacer.
@ldlac peux tu confirmer ?

**Comment by DayField** [comment]
Non bah je suis bien sur master aussi. Je comprends pas j ai rien loupé je suis pas teubé au point. Jvais bien trouver merci bien

**Comment by loko06320** [comment]
Pour ma part , tout marche nikel avec la police en master sauf la distribution de salaire par grade , obligé de mettre le même a tout le monde

**Comment by DayField** [comment]
Merci ! ça doit venir de moi je close

**Comment by ldlac** [comment]
@loko06320 Pas encore dispo, bientôt!
