### ISSUE TITLE
[En service civil] Bug police

### ISSUE THREAD

**Issue by StanG13** [ldlac/La_LifeRP#127]
Salut a tous,

Quand un flic essaye de se mettre en service civil, son skin est give a tout les joueurs connectés sur le serveur. 

Avez-vous un patch éventuel ?

Merci par avance.

**Comment by SirSmog1** [comment]
Apres test même problème pour moi certain joueur on un changement de skin quand un policier prend son service civils

**Comment by ldlac** [comment]
Push pour la stabilité de ce genre de trucs. Étrange. Weird. Mystérieux.

**Comment by StanG13** [comment]
C'est ok pour moi, merci poto
