### ISSUE TITLE
Initializing Session

### ISSUE THREAD

**Issue by SxProject** [ldlac/La_LifeRP#128]
bonsoir je reste bloquer sur Initializing Session 
merci de votre aide.

**Comment by ldlac** [comment]
Si c'est sur Stable, c'est normal parce que c'est plus stable. Je l'ai supprimé

**Comment by SxProject** [comment]
non c'est sur la master

**Comment by ldlac** [comment]
Étrange, ta base de donnée est bien config?

**Comment by SxProject** [comment]
bonjour effectivement j'avais un souci avec ma table problème régler encore merci.
