### ISSUE TITLE
Ban ID ... chat commande

### ISSUE THREAD

**Issue by FreakyMan82** [ldlac/La_LifeRP#132]
Salut tlm!
J'ai une probleme:
 /ban ID, dans la console s'affice http://image.noelshack.com/fichiers/2017/24/5/1497602053-ban-error.png et ca marche pas!

Quelqu'un sait qu'est que c'est ou qu'est que je dois faire?

Merci par avance.

**Comment by SirSmog1** [comment]
ses une commande a faire en jeux /ban id
dailleur je me demande comment on fait pour avoir les ID de joueur sur le framework LaLife

sinon pour la commande console je croix que sais /clientbantemp id ou /clienttempban id
cela ban juskau reboot seulement si je dit pas de connerie

**Comment by FreakyMan82** [comment]
ca je connais (avec icecon ...le ban temporaire), mais dans le jeu la commande /ban id ca marche pas ... j'ai fait une Blacklist ... mais je veux savoir pk ca marche pas la commande dans le jeu (c'est plus rapide) ...

Dsl pour la française, mais je suis pas francais!

**Comment by SirSmog1** [comment]
perso sa marche pour moi /ban id 999999 norp
cependant les gens qui spam pour entrer arrive a leak la ban liste donc pas très efficace

**Comment by FreakyMan82** [comment]
Merci beaucoup, SirSmog1! Desole me je saivais pas qu'il faut ecrire toute la commande.. moi j'ai fait juste /ban id ... pas le temps , pas raison ... mais apparement ca marche bien  ... ;) merci encore !

**Comment by ldlac** [comment]
Dans le rcon faut faire que ban et non /ban
