### ISSUE TITLE
ID Joueurs

### ISSUE THREAD

**Issue by SxProject** [ldlac/La_LifeRP#134]
bonjour comment afficher les ID joueurs aucun touche ne fonctionne
Merci

**Comment by SirSmog1** [comment]
bonne question jaimerais aussi la cmd ou touche pour cette fonction

merci d'avance

**Comment by misterdark441** [comment]
moi aussi

**Comment by ShakirDarwish** [comment]
Faut installer un score bord

**Comment by SxProject** [comment]
ok merci

**Comment by SirSmog1** [comment]
un scoreboard ne donne pas le id des gens au dessue de leur tete ou leur nom comme un /viewname
quand un joueur tue tlm ya pas le temps de voir dans le scorboard qui est qui
faut pouvoir faire /id ou /viewname pour que les admin peuve voir le nom/id au dessus de la tete des joeurs autrement les admins vont jamais y arriver xD

**Comment by SirSmog1** [comment]
il faudrais aussi que le chat affiche le nom rp et nom pseudo se qui pourrais aussi faciliter la tache de ladministration en jeux

**Comment by FreakyMan82** [comment]
jscoreboard --> lien 77 		AddTextComponentString(pid .. " ".. GetPlayerName(v))

 ;)

**Comment by SirSmog1** [comment]
j'ai deja
`		--Name Label
		SetTextFont( 4 )
		SetTextScale( 0.45, 0.45 )
		SetTextColour( 255, 255, 255, 255 )
		SetTextEntry( "STRING" )
		if Settings["PlayerID"] then
			local pid = GetPlayerServerId(v)
		AddTextComponentString(pid .. " ".. GetPlayerName(v))
	   else
			AddTextComponentString(GetPlayerName(v))
		end
		DrawText( 0.015, 0.007 + ( k * 0.03 ) )`

j'ai deja cette config d'entre mais cela donne le pseudo et non le rpname

**Comment by ldlac** [comment]
Un scoreboard sera disponible dans les updates futures avec les noms RP. 
Je vais close en attendant. Parce que ce n'est pas une priorité
