### ISSUE TITLE
Perte des armes en fin de job

### ISSUE THREAD

**Issue by Corn7884** [ldlac/La_LifeRP#135]
Nos armes sont systématiquement retirées in-game (pas en base de donnée) lorsque l'on finis un job et que l'on rend notre véhicule de travail pour récupérer son skin.
Si on déco/reco nos armes nous sont bien rendues
Je suis sur la derniere version master mais le problème existais deja avant

**Comment by ldlac** [comment]
Devrait être fix, je ferme en attendant

**Comment by Corn7884** [comment]
Super merci problème réglé. Et un gros gg pour votre boulot
