### ISSUE TITLE
Bug argents...

### ISSUE THREAD

**Issue by FreakyMan82** [ldlac/La_LifeRP#140]
Bounjour!
Ya un bug avec l'argents ... si un mec (qui est pret d'un autre) il donne d'argents normales/sale avec une somme négatif il prends d'argents d'autre mec et le mec il sera avec la meme some mais négatif. Desole ma francaise!m
Par example: moi je suis pret d'un autre joueur
je fait F7, Donne d'argents, je met la somme -500000... moi j'aurai avec 500000 et l'autre il sera avec -500000. (argents normals ou sale)...

Merci et desole enore pour la langue ... je suis pas francais! ;)

**Comment by ldlac** [comment]
Nice bug, devrait être fix avec le nouvel update.
