### ISSUE TITLE
Heal by alt-F4

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#142]
bonjours certain joueur utilise le alt+F4 ou déconnexion 
pour se revive et ne rien perdre en argent ou autres
avez une option/solution pour remédier a cela

exemple une valeur dans la Sql USER une nouvelle colum Heal qui serais 

0 tu est en vie 
1 tu est mort

et de sauvegarder cette valeur a la deco du joueur
et de la remettre par défaut au reboot serveur (exemple comme les vehicul garage)

Merci d'avance pour vos idee/suggestion/fix

**Comment by Balbz** [comment]
+1

**Comment by buddyqc** [comment]
+1

**Comment by ldlac** [comment]
Je suis sur le cas, je vous tiens au courant

**Comment by SirSmog1** [comment]
merci a vous ;)

**Comment by ldlac** [comment]
Devrait être fix avec la dernière maj. Je vais close, donnez moi des nouvelles.
