### ISSUE TITLE
Faggio2/scooter non revendable

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#143]
Bonjours

les joueurs n'arrive pas a vendre leur faggio2/scooter se qui prend une slot véhicule dans leur garages

possible de rajouter une commande pour /delete un véhicule au garages ?!
pour le faggio2 seulement ...

Merci d'avance

**Comment by buddyqc** [comment]
Achete la pas lolll ou delete la dans mysql

**Comment by SirSmog1** [comment]
il est donner au nouveau par default se qui est une bonne idee mais quil sois bloquer au shop un peux moins

**Comment by ldlac** [comment]
Le bug doit venir de ton côté, parce que moi ça marche parfaitement
