### ISSUE TITLE
Cheat enable? bug argents ...

### ISSUE THREAD

**Issue by FreakyMan82** [ldlac/La_LifeRP#144]
Bonjour!
Vous avez suprime le lien: _DisableScriptHook: true_
Sans ca, tous ils pouvent utilise par ex: lambda menu (j'ai teste comme un joueur normale, pas admin, ca marche) --> pas bon ca ...
Maintenant on peut pas donner d'argents via F7 menu ? 
F7--> Donner d'argents --> mis la some ---> et rien ...  (j'ai pas des erreurs dans la console)
ou... ditez moi qu'est que je doit faire ...

P.S.: Quand j'ai fait la mise a jour, j'ai modifie juste le lien "Propulse par LaLife"... et remplace le dll dans resources --> Wrapper.

Merci par avance!

**Comment by FreakyMan82** [comment]
Apparemment, meme a la banque , tu peut plus donner d'argents!

P.S.: J'ai laisse DisableScriptHook: true ... je sais pas si c'est la cause...

**Comment by dante047** [comment]
Salut j'ai le même soucis j'espère que sa va vite etre fix

**Comment by FreakyMan82** [comment]
il est desactive  ? mais sans le lien du script il marche ... j'ai teste ...alors j'ai laisse DisableScriptHook: true

**Comment by ldlac** [comment]
Réactive le

**Comment by ldlac** [comment]
Je vais voir pour le don d'argent

**Comment by dante047** [comment]
Toujours pas de fix ?

**Comment by FreakyMan82** [comment]
nous attendons ...

**Comment by dante047** [comment]
A ok merci pour votre réponse rapide

**Comment by FreakyMan82** [comment]
de rien ... regarde temps en temps ici dans <Code> ... pour la mise a jour .. ;)

**Comment by dante047** [comment]
ok merci

**Comment by ldlac** [comment]
Je viens de push

**Comment by FreakyMan82** [comment]
Merci beaucoup!
Apparement ca marche! Good job! ;)
