### ISSUE TITLE
Issue running server

### ISSUE THREAD

**Issue by CHansen42** [ldlac/La_LifeRP#147]
Every time i run the server i'm hit by this error on every file i added database info to.

https://i.gyazo.com/58eb2cf389166a439e033530b014e50f.png

I'm sure this is an issue on my end, but i just can figure it out. Database is set up correctly, no errors on the .sql file running.

Any help is much appreciated!

**Comment by buddyqc** [comment]
Do you have unblocked all .dll files?

**Comment by CHansen42** [comment]
are .dll's even a thing on linux?

**Comment by CHansen42** [comment]
just tried it on my windows 10 machine after unlocking the .dll's and still no luck. I should mention im using the Master Branch as the Stable Branch isn't available at the time of writing this.

**Comment by CHansen42** [comment]
Is there more to the installation then whats in the installation.md? i feel like this should be working. Dll's unblocked, Mono is installed. Database correctly installed.  Just can't figure out whats causing these errors.
