### ISSUE TITLE
Sauvegarde métier

### ISSUE THREAD

**Issue by Balbz** [ldlac/La_LifeRP#149]
Lors de la déconnexion, nous devons retourner au pole emploi reprendre un travail à notre reconnexion.
Le jobs ne semble actuellement pas chargé au spawn du personnage.

**Comment by ldlac** [comment]
Le job se sauvegarde dans la base de donnée et est transmis au client lors de la connexion. Pour l'avoir test plus de 20 fois hier, je confirme que oui :)!
