### ISSUE TITLE
Probléme d'envoi en prison

### ISSUE THREAD

**Issue by Balbz** [ldlac/La_LifeRP#151]
Si une personne est menotté/forcé de suivre un policier, si le policier ne prend pas le temps de démenotté la personne il ne pourra pas la mettre en prison, il finira donc pas spammer le bouton du menu ce qui en résultera par une phrase "Toute les cellules sont occupés".

Pensez à rajouter une condition ;) !

**Comment by ldlac** [comment]
Pourtant lorsqu'on envoie une personne en prison, il faut que la cible soit menottée. Et oui en ce moment si le policier spam en fou, c'est comme s'il envoyait quelqu'un dans la prison, donc il faut ouvrir les cellules ou engager de meilleur policier.

**Comment by SirSmog1** [comment]
la prison ses les cellule dans le sous sol du comico ?! ou vraiment a la prison prison .... ?

**Comment by ldlac** [comment]
Sous sol du comico
