### ISSUE TITLE
add jail database

### ISSUE THREAD

**Issue by andslasher123** [ldlac/La_LifeRP#152]
can you please make a better jail script with a database that anybody that reconnects to the server must continue to serve their jail time. Also they are sent to the big prison and not the cell.

Pouvez-vous faire un meilleur script de prison avec une base de données que toute personne qui se reconnecte au serveur doit continuer à servir son temps de prison. Ils sont également envoyés à la grande prison et non à la cellule.

**Comment by ldlac** [comment]
Oui éventuellement, l'important était d'avoir un script fonctionnel. Libre à vous de ban les gens qui se déco durant leur sentence.
