### ISSUE TITLE
Remboursement du camion

### ISSUE THREAD

**Issue by TonTonSheitan** [ldlac/La_LifeRP#154]
Salut, depuis la dernière maj, quand je vais au pole emploi pour changer de métier sur certains métier sa me donne 3000$ et sa me dit que mon camion a était remboursé, quelqu’un a le même problème que moi ? 

Merci pour vos réponse et votre aide 

++

**Comment by ldlac** [comment]
Bon point, je viens de push des hotfix qui devrait régler

**Comment by TonTonSheitan** [comment]
Merciii
