### ISSUE TITLE
Erreur apres mise a jour

### ISSUE THREAD

**Issue by NikoDEK** [ldlac/La_LifeRP#155]
Bonjour, je viens de suivre vos Commits on Jun 22, 2017
Refactor des jobs legal, Pôle emploi fonctionnel
ldlac committed 11 hours ago
Fix weapons, now working.
ldlac committed 14 hours ago
Fix weapons
ldlac committed 15 hours ago
Fix amendes
ldlac committed 17 hours ago
Fix Alt F4 and Weapons lost on character update
ldlac committed 17 hours ago

est la gros problème j'ai les erreurs suivantes et quand je lance mon serveur sur fiveM il ne se lance pas :/ saviez vous a quoi est du cette erreur?

http://hpics.li/8a0d476
http://hpics.li/32da7c7
http://hpics.li/6a92dfc
merci d'avance

**Comment by Corn7884** [comment]
Meme souci pour moi mais seulement depuis la maj Refactor des jobs legal, Pôle emploi fonctionnel
ldlac committed 11 hours ago

**Comment by StanG13** [comment]
Idem.

**Comment by NikoDEK** [comment]
moi j'ai fait les 5 d'affilés donc impossible de s'avoir le problèmes mais du coup sa doit être a cause de la maj Refactor des jobs legal, Pôle emploi fonctionnel
ldlac committed 11 hours ago

**Comment by StanG13** [comment]
Je confirme que le bug vient bien de : ldlac committed 11 hours ago

**Comment by ldlac** [comment]
Possible fix de push

**Comment by NikoDEK** [comment]
comment sa ?

**Comment by Corn7884** [comment]
A première vu oui le pb est réglé merci

**Comment by NikoDEK** [comment]
pour ma part j'ai toujours les erreur :/

**Comment by StanG13** [comment]
Le plus gros des erreurs c'est ok, il en reste tout de même quelques une.

**Comment by NikoDEK** [comment]
j'ai reverifier mais modife et la nickel plus d'erreur merci beaucoup :)
