### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by medaion** [ldlac/La_LifeRP#156]
Le lscustom ne sauvegarde pas les modifications dans le garage ...
Plusieurs joueur me dise que cela est un peux chiant surtout quand il paye leur modifications ...

**Comment by ldlac** [comment]
Le lscustoms est désactivé par défaut entre autre pour cette raison.

**Comment by medaion** [comment]
lol , vous conté pas le corrigez ...

**Comment by ldlac** [comment]
Pas encore, il y a des trucs plus important, le temps nous manque. Si des gens veulent le faire, pourquoi pas. Nous sommes 2, c'est impossible tout fix dans un si court laps de temps. Je t'invite à faire une pull request avec une version améliorée :)!

**Comment by medaion** [comment]
Ok , je comprend , j'avoue qui reste encore beaucoup a faire & déjà c'est une bonne base .
Et je vous remercie pour le travail que vous faite pour la communauté .
Si je trouve la solutions je vous enverrais le code source de l'implantations ... 

Merci pour le travail que vous faite continué vous êtes parmi les meilleurs core.
