### ISSUE TITLE
Problème bizarre

### ISSUE THREAD

**Issue by DarkZiko** [ldlac/La_LifeRP#157]
Je veux aller dans le serveur et sa me donner un message, Regarder les images pour voir ce qui est écris!

Cordialement,
DarkZiko
![capture](https://user-images.githubusercontent.com/29645053/27462218-15e6fe28-578d-11e7-9c6f-018a02d0d9d1.PNG)

**Comment by DarkZiko** [comment]
Donc je peux aller dans mon serveur il me dit se message et me load a l'infinie donc peut tu m'aider. Et aussi comment ta fait pour avoir le serveur en copy et le mettre dans githud? Tes un hackeur?

Cordialement,
DarkZiko

**Comment by SirSmog1** [comment]
est tu en local ? sur ton ordinateur perso ?
ou chez un hebergeur ..... ?

**Comment by DarkZiko** [comment]
J'ai teamspeak et discord je peux te passer mon discord en dev et on parlera ou sinon j'ai skype

**Comment by SirSmog1** [comment]
nan mais ton serveur tu le start sur ton ordinateur a toi ou tu paye pour louer une ordinateur et y mettre ton serveur ?

**Comment by DarkZiko** [comment]
non je l'ais sur mon ordi

**Comment by SirSmog1** [comment]
tu arrive a connecter avec lip 127.0.0.1 dans le direct conect ?

**Comment by DarkZiko** [comment]
Oui mais attend je vais faire une vidéo et vous allez voir!

**Comment by DarkZiko** [comment]
Attender un petit problème de Action!

**Comment by DarkZiko** [comment]
Action ne veux pas désoler mais je l'ais fait 127.0.0.1 direct connect après un petit carré rouge aparait en haut vers la gauche. Et la console mets un message d'erreur et sa me load à l'infinie

**Comment by DarkZiko** [comment]
Crois tu que ses la whitelist ou un bug que ta jamais vu?

**Comment by buddyqc** [comment]
As tu modifier les fichiers du serveur?

**Comment by buddyqc** [comment]
Sinon pense a vider ton cache de client et serveur

**Comment by DarkZiko** [comment]
non pas du tout

**Comment by DarkZiko** [comment]
faut que je suprime http-file

**Comment by DarkZiko** [comment]
Bien toute les fichier de http-files faut les suprimer?

**Comment by buddyqc** [comment]
Oui toutes les fichiers dans http-files

**Comment by buddyqc** [comment]
As tu pris les derniers fichier serveur de fivem mise a jours et installer la derniere version master de la life? Ont dirait une modif des fichiers

**Comment by DarkZiko** [comment]
il faut le retélécherger et mettre sa mise a jour

**Comment by DarkZiko** [comment]
j'ai retélécharger pour avoir les mise a jour et j'ai supprimer tout dans http-files

**Comment by DarkZiko** [comment]
Encore le même message!
![capture](https://user-images.githubusercontent.com/29645053/27487792-b2b9fbae-5802-11e7-933f-d21f97c71038.PNG)

**Comment by DarkZiko** [comment]
Voila se que disait se message : 
«Un client a essayé d'envoyer un événement de type, mais il ne s'agissait pas de l'invocation du client. Vous devrez peut-être appeler RegisterServerEvent à partir de votre script.»

**Comment by DarkZiko** [comment]
???

**Comment by DarkZiko** [comment]
Je sais il faut télécherger lalife après le lancer et sa fonctionne mais pour moi quand je essaye de me co sa me load à l'infinie

**Comment by CHansen42** [comment]
Avez-vous encore cette solution?

**Comment by DarkZiko** [comment]
Un youtubeur ma dit de mettre le mot de passe du serveur dans la base de donne sur phpmyadmin. il faut faire sa? où sa marchera pas?

**Comment by ldlac** [comment]
Vu que le problème est personnel, je vais close, vous pouvez continuer la discussion.

**Comment by DarkZiko** [comment]
Idlac toi ta pas eu se problème une fois et si-oui comment on règle sa?
![capture](https://user-images.githubusercontent.com/29645053/27520844-24d5769c-59e2-11e7-997b-2279343bbd14.PNG)

**Comment by ldlac** [comment]
Normalement ce problème vient de la base de donnée qui est mal configuré, mais c'est dur à dire

**Comment by DarkZiko** [comment]
Comment on fait pour la remettre à sa place?

**Comment by DarkZiko** [comment]
Parce que moi j'ai vérifié tout les fichiers et même avec phpmyadmin, j'ai regarder et j'ai pas été capable de trouver se fichier ou la base de donner!

**Comment by DarkZiko** [comment]
Un pote ma dit que il faut configurer dans un fichier et autoriser l'accès au serveur.
