### ISSUE TITLE
MASSE ERROR depuis la maj de FIVEM

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#159]
https://image.noelshack.com/fichiers/2017/25/5/1498234706-screenshot.png

**Comment by SirSmog1** [comment]
ca ne viens pas de la maj de fivem ... sa viens du login.lua de ton serveur ;) dans essentials je croix

**Comment by Julian51100** [comment]
nan dutout cas sa marcher parfaitement avant :(

**Comment by buddyqc** [comment]
As tu mis a jour la life et oublier de debloquer les .dll?

**Comment by Julian51100** [comment]
nan car c'est seulement depuis la mise a jours de stapremidi, 
la nouvelle version marche pas pour moi :(

**Comment by Julian51100** [comment]
donc ce matin tout marcher correctement et la boum sa fait sa :( 
chargement infini et tout :(

**Comment by Julian51100** [comment]
meme avec l'erreur lambada sa marcher avant hors que la sa fait chargement infinie seulement depuis la maj :(

**Comment by Julian51100** [comment]
Problème réglé, erreur login corriger ;)
files  stream désactivé et réactivé et c'est good ;)
