### ISSUE TITLE
Probléme jobs mineur

### ISSUE THREAD

**Issue by TonTonSheitan** [ldlac/La_LifeRP#161]
Salut, depuis votre dernière MAJ sur les métier légal, ya un petit problème avec le jobs de mineur:

-Je peut sortir mon camion et sa me retire l'argent, mais au moment de rentré le camion, il me rentre bien le camion et sa me rembourse et c'est la qu'arrive le problème sa me dit toujours appuyer sur E pour ranger votre camion même si ya plus de camion donc je me fait +3000$ a chaque fois que j'appuie sur E et donc je ne peut plus faire mineur. 

Voila merci pour votre aide, réponse et votre taff.

++

**Comment by Julian51100** [comment]
slt, esque ta sa survton serveur dans les fichier , 
LaLifeRP-Wrapper-Source

**Comment by Julian51100** [comment]
quel source a tu ?

**Comment by StanG13** [comment]
Pareil sur mon serveur, c'est confirmé par un joueur.
et j'ai :
LaLifeRP-Wrapper-Source

**Comment by TonTonSheitan** [comment]
La solution:

-Dans le paragraphe    function mineEnding()   ligne:488
-ajoute    camionSortie = false

Perso je les mis en dessous de "money = 0" et sa fonctionne parfaitement.

Merci a Irtas Momaki pour la solution

**Comment by NikoDEK** [comment]
j'ai tester la solutions et rien na faire toujours le même probleme

**Comment by TonTonSheitan** [comment]
tu a du faire une erreur quelque part car je confirme que sa marche bien a 100%

**Comment by TonTonSheitan** [comment]
![screenshot_20170624210632](https://user-images.githubusercontent.com/28569092/27511297-0d775608-5921-11e7-84f2-b0565f5781b5.png)

**Comment by NikoDEK** [comment]
oui oui je les mit au meme endroit :/

**Comment by StanG13** [comment]
C'est ok pour moi, merci.

**Comment by StanG13** [comment]
*Meme avec les 3000 € dispo en espece impossible de payer la caution pour avoir camion de poubelle 
*Quand le camion de nettoyeur de piscine est ramener a l'endroit, on nous signale "appuyer sur E pour ramener le camion" comprenez reprendre votre caution de 3000 €, malheusement camion toujours devant nous et dite aurevoir a votre caution de 3000 € !

**Comment by ldlac** [comment]
Je viens de push un fix pour la caution de la mine qui pouvait devenir abusive si spammé.
Par contre je ne vois pas le bug pour trash ou pooljob, tout fonctionne bien de mon côté.
