### ISSUE TITLE
Verrouiller le véhicule

### ISSUE THREAD

**Issue by CHansen42** [ldlac/La_LifeRP#167]
Vous pouvez verrouiller un véhicule, mais lorsque vous l'ouvrez, il ne s'allume pas.

**Comment by bozoweed** [comment]
c'est la maj fivem qui fait ça je ne donne pas le fix mais il faut regarder dans le dossier client_base et éditer le lock.lua du coter client

**Comment by SirSmog1** [comment]
pourquoi ne pas lui donner le fix ?! .....

**Comment by bozoweed** [comment]
Car avec un peut de recherche dans le script et sur native.db on trouve la solution en 2 minutes je vais pas non plus lu essuyer le popo

**Comment by bozoweed** [comment]
Si il trouve pas d'ici demain je le donne mais essayer d'apprendre un peut au lieu de faire des simple copier coller

**Comment by bozoweed** [comment]
lol smirsmog qui me dislike just pck je veut vous apprendre a déveloper quelle abr**i

**Comment by CHansen42** [comment]
Je l'ai réparé avant même d'avoir posté ceci. Je les fais savoir simplement afin de pouvoir réparer la branche maîtresse

**Comment by bozoweed** [comment]
un vrai dev c'est cool , daans ce cas merci de ta façon de report les bug :)

**Comment by buddyqc** [comment]
Le issue ne serve pas ridiculiser le monde mais a sentraider dude alors si tu veux pas le donner ta juste a la fermer pis pas repondre

**Comment by bozoweed** [comment]
Buddy je comprend ta reponse mon but n'est pas de ridiculise mais de lui faire comprendre que mon message était pour les aider a comprendre le code de gta et non pas donner une reponse tout cuit mais comme il ma chauffer a me dislike gratuit je lui est fait comprendre la vie

**Comment by SirSmog1** [comment]
lolll bozoweed ses pas tlm qui sais coder en .lua 
CHansen42 a peut etre 11 ans .... et cherche seulement un fix pour son problème ....

si tu a la solu donne la et puis sinon laisse tomber d’écrire ici .....
c'est a cause de l’attitude des gens comme toi que sur FiveM sa avance a reculons

pour ton info oui j'ai 1 serveur qui tourne casi toujours full ;) h24

je suis ici pour aider si un simple pousse te mais dans cette état laisse tomber l'aide au autres

a close + sup merci

**Comment by bozoweed** [comment]
Lol alors pourquoi toi tu n'as pas donner la reponse ? Bref je vais delzte tous mes poste c'est justement de guigniol comme vous , qui voulait absolument la reponse sans comprendre pourquoi on  lr code comme ca que fivem cest de la merde et que la commu gta  me fait vomir sur ceux ciao

**Comment by SirSmog1** [comment]
je n'est pas la réponse et non plus ce probleme ...
je trouvais ca juste degeux que tu est le fix mais que tu fasse attendre la personne ..

un copier coller ses pas la fin du monde ......

si tu veux apprendre quelque chose a quelqu'un fait un tuto icit ses pour aider ou report

**Comment by loko06320** [comment]
du coup si tu peut partager ta correction ou en faire  une pull request stp , afin que les autres puissent en profiter

**Comment by CHansen42** [comment]
J'ai ajouté un système de verrouillage différent, de sorte que cela ne se passera pas
