### ISSUE TITLE
Menu f7 Véhicules

### ISSUE THREAD

**Issue by DayField** [ldlac/La_LifeRP#17]
Dans les véhicules, quand on press f7 on ne peut plus rien faire et surtout quand on ferme le menu, on est mis hors du véhicule, icydk

**Comment by ldlac** [comment]
Idéalement c'est le but envisagé. Pas encore au point. On est éjecté à cause de l'animation qui se déclenche

**Comment by DayField** [comment]
ouais voilà le télephone au volant empêche de rouler pourquoi pas mais galère pour l éjection :/

**Comment by WalterWhite84** [comment]
C'est une excellente idée ceci le seul problème c'est l’éjection car finalement en passager on peut très bien utiliser sont téléphone :)

**Comment by ldlac** [comment]
Devrait être réglé. Animation téléphone que lorsqu'on est dans répertoire. Plus possible d'accéder à répertoire dans un véhicule.
