### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by IRemake** [ldlac/La_LifeRP#179]
Bonjour,

Je voudrais ajouter un disclaimer à la connexion de mes joueurs mais j'ai le logo de la life RP qui se met en plein milieux je voulais savoir comment je pouvais faire pour l'enlever le disclaimer viens de la : https://forum.fivem.net/t/release-simple-disclaimer/24540
Une image pour comprendre mon problème : https://gyazo.com/32f988ab8a52c417e55b24fa197e601f?token=ef516cbec447a2318dbf0e121deb6007

**Comment by NikoDEK** [comment]
dans le fichier resources/[citizen]/motd/ui/img tu as l'image a modifier pour ton disclaimer du coup tu creer l'image que tu veut et tuas ton disclaimer perso ;)

**Comment by IRemake** [comment]
Merci à toi je vais tester sa directement
