### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by Beb0p** [ldlac/La_LifeRP#18]
Actuellement on reçoit nos propre SMS lorsqu'on les envoient a nos contacts
Et tous les joueurs en ligne reçoivent les SMS envoyés.

**Comment by Lariime** [comment]
Même problème.
Merci Idlac pour l'Open Source, ca nous a permis de sauver un serveur sous extended en une nuit ;)

**Comment by ShakirDarwish** [comment]
Pour les sms nous somme au courant nous allons patch tout sa sous peux

**Comment by sim2511** [comment]
une sauvegarde des messages reçus serait pas mal aussi ! :)

**Comment by RyUkApples** [comment]
Un historique ouais

**Comment by ldlac** [comment]
Éventuellement pour l'historique.
