### ISSUE TITLE
Pas de menu ou téléphone ou inventaire...

### ISSUE THREAD

**Issue by funzik** [ldlac/La_LifeRP#190]
Bonjour, je viens de télécharger votre serveur et je l'ai installer sans souci, je n'ai pas encore changer bcp de choses (juste le fichier dll pour changer "propulsé par...", puis des voitures dans le dossier LSPD, puis le nom du serveur dans citymp, et le nom des voitures dans le menu police) et pourtant je ne peut pas faire apparaitre le menu qui notamment contient le téléphone je crois et des fonctions pour les policiers et puis comment manger ou boire du coup etc... est ce normal? y'a til quelque chose à activer ?

**Comment by b4b4s666** [comment]
les fonction du cellulaire son integrer au dll que tu a modifier pour enlever propulser par !!

**Comment by funzik** [comment]
effectivement en remettant le dll original, le téléphone refonctionne et les menus police aussi... dommage les sources servent finalement à rien...
