### ISSUE TITLE
Modifications payement de l'essence

### ISSUE THREAD

**Issue by NikoDEK** [ldlac/La_LifeRP#28]
Bonjour je ne trouve plus les modifications qu'il faut apporter pour le paiement de l'essence savez vous ou je peut les trouver ? 
merci d'avance

**Comment by DayField** [comment]
je m en occupe, faut que je change deux trois trucs avant et tu auras un tuto dans le fichiers modification

**Comment by NikoDEK** [comment]
D'accord merci beaucoup super bonne idee en tous cas ,merci a vous tous pour se super taff que vous faites

**Comment by ldlac** [comment]
Devrait être réglé. Se trouve dans foodhud > price.lua
