### ISSUE TITLE
Menotter/Faire monter dans le véhicule

### ISSUE THREAD

**Issue by Hyakkimaru** [ldlac/La_LifeRP#29]
Deux bugs potentiels (ça semble fonctionner chez certains mais pas chez d'autres) : 

1 - Quand on menotte quelqu'un et qu'on le force à suivre, même en arrêtant l'action (via le menu F7) et même en arrêtant le service du policier, le menotté continue de suivre.

2 - Forcer les gens à monter dans le véhicule de police ne semble pas fonctionner non plus.

**Comment by WalterWhite84** [comment]
Pour le soucis de suivre cela fonctionne super bien perso mais également un soucis pour faire monter et descendre les gens des voitures cela ne fonctionne jamais .

**Comment by ldlac** [comment]
Il faut être DANS le véhicule en question

**Comment by ldlac** [comment]
C'est pas écrit nulle part, il faut le deviner

**Comment by ldlac** [comment]
Fonctionne à 100% avec l'update. Je vais mettre des explications pour savoir comment ça fonctionne exactement
