### ISSUE TITLE
serveur

### ISSUE THREAD

**Issue by misterdark441** [ldlac/La_LifeRP#30]
bonjour voila mon problème quand je suis avec mon amis sur le serveur au bout d'un moment je le voie plus dans la liste des joueur je le voie pas ou il me dit ou il es mais quand il écris dans chat ou quand il se déconnecte je voie le message je sais pas si sa viens du serveur de lui ou de mon hebergeur si quelqu'un a déjà eu le problème hésite pas me le dire

**Comment by FeaReDGlock** [comment]
Jcrois que c'est un beug d'instance ou un truc dans le genre nn ? Normalement il doit deco reco

**Comment by misterdark441** [comment]
oui mais sais tout 5 minute est ce que sais corrigeable

**Comment by FeaReDGlock** [comment]
Ouais, surement mais personnellement je serais pas te dire comment faire !

**Comment by Julian51100** [comment]
j'ai ce bug :(

**Comment by Julian51100** [comment]
comment le corriger ?

**Comment by IRemake** [comment]
C'est un changement d’hôte c'est à cause de ta machine (J'ai le même problème et j’espère pouvoir le régler avec une machine plus performante) techniquement sa viendrais de ta machine j'ai énormément de desync aussi

**Comment by Julian51100** [comment]
c'est a dire ? 
ta suoi comme machine ? 
moi j'ai un vps windows 2008 R2 avec 4go de ram et 200 mbps

**Comment by Julian51100** [comment]
pourtant le serveur tourne a merveille aucun lag etc

**Comment by Julian51100** [comment]
fin j'comprend pas avec une autre source (repack brk) sa tourne bien
