### ISSUE TITLE
Trop de connexions

### ISSUE THREAD

**Issue by nmaroine** [ldlac/La_LifeRP#31]
Bonjour,
apres avoir chargé la DLL SQL async je me retrouve avec cette erreur
avez vous rencontré des problèmes ?
![image](https://cloud.githubusercontent.com/assets/17453646/26702174/1c5412f6-4724-11e7-8aa3-2d3f778ff89d.png)

**Comment by joelwurtz** [comment]
On est train de corriger cela, les dernière versions devrait deja être mieux
