### ISSUE TITLE
[Error]Chargement infini ...

### ISSUE THREAD

**Issue by nmaroine** [ldlac/La_LifeRP#36]
Bonjour,
apres le Hot fix de ce matin, effectivement il y plus l'erreur des connexion ouverte et non fermer, mais actuellement le serveur ne démarre plus, un chargement infinie et aucune erreur dans les logs.
est ce que ça marche chez vous ?
merci d'avance
voici mes Log : (serveur normal sous windows Serveur 2012 R2)
![image](https://cloud.githubusercontent.com/assets/17453646/26714459/beba576a-4771-11e7-8aac-7cf30e7520b0.png)

![image](https://cloud.githubusercontent.com/assets/17453646/26714545/2fdc28ec-4772-11e7-880d-e5d21a809979.png)

![image](https://cloud.githubusercontent.com/assets/17453646/26714555/3c190882-4772-11e7-969d-649649c2738e.png)

![image](https://cloud.githubusercontent.com/assets/17453646/26714564/483b8950-4772-11e7-9c2a-337d866433fa.png)

**Comment by WalterWhite84** [comment]
Exactement le même problème et également un problème au niveau de la base de données qui s'installe pas http://prntscr.com/fezhib

**Comment by Meutledaron** [comment]
Pour ton soucis WalterWhite84, supprime simplement le début de la base a savoir tout ce qui est entre /* et */, ce sont des commentaires en php. 

Pour des commentaires en sql il faut utiliser --

**Comment by ig0ne** [comment]
Pour ma part aucune erreur dans la console mais j'ai bien un chargement infini et comme je viens de tester le mod je voie pas d’où peux venir le problème (première installation donc propre)

**Comment by n3wb0rn84** [comment]
Même erreur que nmaroine , les mêmes logs apparaissent mais pour ça , je dois quitter le jeu sur mon pc et ensuite le serveur fini par me dire la même chose que nmaroine !

J'ai remis la BD à neuf étant donné le côté medic et ne voulant pas faire d'erreur , et rien ne fonctionnait , je me suis donc dit " reessayons avec l'ancien serv sans la maj pour me relog sur la BD " , étant donné que je l'ai remise à neuve à la base donc rien dedans ! 

Et là en ayant rejoins mon serv avec l'ancienne version , m'être délog et relancé le serv avec la nouvelle version , j'arrives à me connecter ! 

Je penses qu'une erreur à la création d'un nouveau joueur dans la BD , fait bugger ! 

J'ai fait un test avec un ami non enregistré dans la BD et moi enregistré dedans , il n'arrives pas à se co et moi je joues nickel ! 

Si ça peut vous éclairer ! Moi j'ai trouvé que ça pour tester !

**Comment by joelwurtz** [comment]
Corrigé par  https://github.com/ldlac/La_LifeRP/pull/40

un peu de patience :)

**Comment by ldlac** [comment]
Merged
