### ISSUE TITLE
[Pas confirmé] Item custom n'apparaissent pas (branche Master)

### ISSUE THREAD

**Issue by Hyakkimaru** [ldlac/La_LifeRP#37]
J'ai voulu créer un item custom, une bouteille d'eCola pour être précis.

Donc j'ai fait l'ajout en DB, j'ai rajouté une ligne aussi dans inventory.lua, vidé mon cache et je peux acheter la bouteille sans problème par contre dès que j'ouvre le menu F7, elle n'apparait pas, dans la DB elle est bien notée dans user_inventory.

A priori pas d'erreur dans la console F8 et pas plus non plus dans celle du serveur.

**Comment by ldlac** [comment]
As tu ajouté d'autres items? La gestion des items est un peu merdique en ce moment, je vais devoir faire quelques getData de la db parce que là c'est souvent hardcodé dans le code

**Comment by Hyakkimaru** [comment]
J'ai réessayé, pareil, l'item n'apparait pas :/

De toute façon à terme j'imagine que tu vas faire évoluer le truc pour que ça fonctionne par type et plus par ID ?

**Comment by ldlac** [comment]
Devrait être fix avec le patch de login.lua.
Il faut 1. Ajouter à la bdd et 2. ajouter à inventory.lua
