### ISSUE TITLE
Menu qui disparaît après achat nourritures/vêtements

### ISSUE THREAD

**Issue by Debug411** [ldlac/La_LifeRP#4]
Bonjour, 

Petit problème avec le menu après l'achat de nourritures et la modification (skin) du personnage. Impossible de faire réapparaître celui-ci.

**Comment by ldlac** [comment]
Télécharge la nouvelle version! :)

**Comment by Debug411** [comment]
Autant pour moi, je n'ai pas fait la maj ! Je vous tient au courant, je modif certains scripts et fait les tests au fur et à mesure ! Merci de la rapidité pour la réponse ^^
