### ISSUE TITLE
Vous n'êtes pas en service (Branche Master)

### ISSUE THREAD

**Issue by Draxprodd** [ldlac/La_LifeRP#44]
Bonjour :)

Petit soucis sur le Branche Master si vous n'êtes pas au courant.
Quand on est en Policier, et que l'on veux prendre un véhicule, impossible, "Vous n'êtes pas en service", alors que nous le sommes bien vu que nous avons la tenue, nous avons accès au menu Police etc..

Merci à vous

**Comment by IRemake** [comment]
J'ai le même problème que Draxprodd je sais d'où vient ce problème sa vient du enService qui ne passe pas à 1 il reste à 0 à pars modifier le script et de faire passer le "if == 0" pour que sa marche je sais pas comment faire sa doit être une requête qui met pas enService à 1 quand on prend nôtre service voilà

**Comment by ldlac** [comment]
Va être fix au prochain push.
L'info n'était pas get vers le menu
