### ISSUE TITLE
DLC appartements 

### ISSUE THREAD

**Issue by Lapatateaz** [ldlac/La_LifeRP#45]
• APPARTEMENTS

+ Des appartements achetables
 Intéractions dans appartement personnel (Stockage / Coffre fort Argent Sale  / Garage véhicule / Alcool...)
 Possibilitée de rendre visite dans un appartement d'un amis (sonnette a l'entrée des bâtiments)
 Police : Perquisition appartement
 Carte identitée : Adresse 

Il y'aurais t'il une possibilité d'avoir ceci ?

**Comment by ldlac** [comment]
Oui c'est prévu
