### ISSUE TITLE
Problème avec l'achat des armes [ branche stable] et une erreur apparaît avec le mysql-async [ branche master]

### ISSUE THREAD

**Issue by Novamiiro** [ldlac/La_LifeRP#48]
Quand j'achète une arme je ne les pas dans mon inventaire je ne sais pas si ces moi qui est fait une bêtise ou pas.
Quand je démarre le serveur il y a une erreur a la fin du chargement de tout les scripts et quand j'essaie de rentré dans le serveur j'ai que des erreurs et un chargement infini je sais pas non plus si j'ai fait une bêtise ou pas

**Comment by ldlac** [comment]
Je reçois bien mes armes perso.
