### ISSUE TITLE
point de travaille (traitement/vente/recolte)

### ISSUE THREAD

**Issue by smixiop** [ldlac/La_LifeRP#51]
lorsque on prend un travail on peux voir  tout les point des autre travaille  une solution ?

**Comment by RyUkApples** [comment]
Faudrais set une permission pour voir les blips.. Rien de plus simple

**Comment by ShakirDarwish** [comment]
Tout les blips sont instancier de base, tu as simplement as regarder dans la ressource mine et de t'inspirer pour les blip
