### ISSUE TITLE
Comment changer le logo ?

### ISSUE THREAD

**Issue by Matheo2778** [ldlac/La_LifeRP#55]
Bonjours je susi actuellement en train de tester votre source. Je voudrais savoir comment changer le logo dans le menu f7 ou autre ... Merci de votre aide 👍

**Comment by YoutubePlayFunOnline** [comment]
Bonjour,

- Voir dossier ressource.
- Allez dans fivemenu.
- Ouvrir le dossier stream.
On peux y voir un fichier qui s'apelle "fivemenu.ytd".

- Ouvre le avec OpenIV.
- Active le "Edit Mode"
- Puis ouvre le "fivemenu.ytd" en double cliquant dessus.
Tu peux y apercevoir les textures du menu.
- Clique sur "Export All"
- Ensuite tu choisis de les Exporter en ".PNG"
- Ensuite il sont sur ton bureau ou autre.
Tu peux desormais les modifier avec Photoshop ou Paint.
- Quand les textures sont modifier tu peux enfin les remettres dans OpenIV.
- Une fois les textures glisser dans OpenIV clique sur "SAVE"

Voila tu peux ré-utiliser ton "fivemenu.ytd"

Par contre laisse un minimum de crédits il bosse sur un open source sa serai cool pour eux.
Merci Cordialement AxGHD de la PlayFunOnline.

**Comment by Matheo2778** [comment]
Pas de soucis ;) de tout de façon c'est un serveur test ! Je laisserai les crédits sur le serveur officiel

**Comment by Matheo2778** [comment]
@YoutubePlayFunOnline Heu ... J'ai reussi a exporter ma texture je l'ai modifier mais je ne trouve pas comment la ré-importer sur openIV

**Comment by Matheo2778** [comment]
Autant pour moi ... Je viens de reussir

**Comment by fabs63** [comment]
Bonjour, en ce qui me concerne je n'arrive pas à l'ouvrir, open me demande d'ouvrir le dossier du jeu gta seulement
