### ISSUE TITLE
Ambulancier

### ISSUE THREAD

**Issue by MagnanQC** [ldlac/La_LifeRP#56]
Allo,

Lorsqu'on ai dans le coma, et qu'il y a un medic de connecté, impossible de l'appeler (normal on ai dans le coma), mais lorsqu'il vient à nos coter impossible pour lui de nous recussite où nous administrer les soins.

Merci

**Comment by ldlac** [comment]
J'ai testé à plusieurs reprises et lorsque le medic est connecté et en service, ça fonctionne très bien. On l'appelle lorsque l'on est dans le coma en effet.

**Comment by MagnanQC** [comment]
non, lorsqu'on fait "E" sa respawn...

**Comment by Guyplay** [comment]
pareil quand je fais e sa respawn :/

**Comment by DayField** [comment]
Testé ça marche pour moi

**Comment by MagnanQC** [comment]
Nous somme sur master

**Comment by FeaReDGlock** [comment]
Perso quand je meurt, je peut que faire X quand un médic est la et des que je fait E je respawn et sa m'affiche le message mais rien apres !

**Comment by ldlac** [comment]
Je viens de test ce soir et tout fonctionne bien. À voir

**Comment by MagnanQC** [comment]
De mon coter sa fonctionne avec la derniere master !
Je close, Merci a toi @ldlac :)
