### ISSUE TITLE
Pôle d'emploi 

### ISSUE THREAD

**Issue by MagnanQC** [ldlac/La_LifeRP#57]
Lorsque les gens décroche un emploi dans le pôle d'emploi tout les gens connectés reçoivent la notification.

Example: joueur1 prend l'ambulanciers, joueur2,3,4 etc reçoivent la notification du genre "félicitations vous êtes ambulancier"

Prendre note que le bug est bien au niveau de la notification étant donner que les joueur2,3,4 non pas décrocher l'emploie (selon SQL)

Merci pour votre build gang :)

**Comment by ldlac** [comment]
Ouais, je travaille encore sur ce genre de bug qui me semble très très mystérieux jusqu'à maintenant

**Comment by RyUkApples** [comment]
Idlac quel fichier je peux t'aider ;) ??

**Comment by ldlac** [comment]
poleemploie_server et tel_server et un peu dans login pour le tel. Mais ça semble être la source qui part en couille

**Comment by RyUkApples** [comment]
J'ai pas check, je sais pas a quoi ca ressemble le code que tu a fais, j'irais voir apres, mais tu n'a pas fais de GetPlayerPed -1 .. ? Mais sinon je vais check et si je trouve le prob jte le met en pull

**Comment by RyUkApples** [comment]
Moué c'est chelou tout est en source, je vois pas le problem O_o

**Comment by RyUkApples** [comment]
J'ai peut etre trouvé un fix je le test actuellement, si il marche je le met en pull request

**Comment by ldlac** [comment]
Je crois avoir trouvé le bug, ça vient des nouveaux users qui se connectait. Mais tu peux montrer ton fix ça ne peut pas nuire :)

**Comment by RyUkApples** [comment]
Marche pas, j'ai testé :/ du coup publie le tiens

Au passage je compte publier quelques trucs/fixes pour aider a améliorer la source ^^

Voili voulou, encore bonne chance a toi 

Cordialement, Ryuk RED

**Comment by ldlac** [comment]
Oui n'hésite pas. Tu peux passer par le pull requests ou directement par moi en pm si tu comptes implanter un truc avec une structure différente

**Comment by MagnanQC** [comment]
Sa semble etre fix .. du moins pour la derniere version master.

Libre a vous de fermer l'issue, je sais pas si les autre usager on le meme probleme..

**Comment by ldlac** [comment]
Oui les notifications globales semblent en effet avoir été fix avec mon dernier patch. Reste à peaufiner le pole emploi.

**Comment by FeaReDGlock** [comment]
SI c'est Fix pensez a close le sujet :)
