### ISSUE TITLE
Target police

### ISSUE THREAD

**Issue by MagnanQC** [ldlac/La_LifeRP#59]
Re-bonjour,

Possible que ce soit moi le problème, mais j'y vais quand même.

Lorsque je suis policier, il faut que je "target" le joueur pour lui demander ses papier. Or, je le pointe avec mon fusil mais impossible d'engager la demander ou faire tout autre commande de police.

As-t'il une façon pour "target" ? Ou bien il faut vraiment pointer avec son arme ?

Merci d'éclairer la situation :)

**Comment by ldlac** [comment]
Pour "Target" il faut se trouver à quelques mètres de la cible, c'est à dire, très proche. Ouvrir le menu F7 à ce moment là. Et ça devrait fonctionner.

**Comment by MagnanQC** [comment]
je confirme que sa fonctionne pas.

Je vais mettre une capture ici du jeux

**Comment by MagnanQC** [comment]
Fix.
