### ISSUE TITLE
Supprimer le System de Job

### ISSUE THREAD

**Issue by Matheo2778** [ldlac/La_LifeRP#60]
Bonjours, je souhaiterai supprimer le systeme de job pour mettre celui la https://github.com/PandaBasketteur/Jobs-System-and-Paycheck 
Mais je n'arrive pas :/ Quelqu'un pourrait m'aider ?

**Comment by Matheo2778** [comment]
(Car je voudrais utiliser vdk recolt mais je n'arrive pas a delete le job system disponible dans le fichier resource)

**Comment by ldlac** [comment]
Techniquement c'est celui que je me suis inspiré mais il est grandement modifié

**Comment by IRemake** [comment]
mais la grande question est pourquoi tu veux mettre vkrecolt ? on a système de récolte qui marche du tonnerre de dieu et un systeme de police qui marche aussi

**Comment by sim2511** [comment]
ça part dans tous les sens, tu veux supprimer un système de job qui a été améliorer pour le remplacer, après tu changes de sujet en parlant du système de récolte. Je veux pas paraître négatif mais tu devrais poser tes questions sur discord. A bon entendeur
