### ISSUE TITLE
Mauvaise Utilisation d'objets

### ISSUE THREAD

**Issue by rvwarrior** [ldlac/La_LifeRP#62]
Voici un bug assez gênant: il est possible "d'utiliser" un item dans l'inventaire, par exemple: utiliser la bouteille d'eau vous fait boire. Là où cela devient gênant, c'est lorsque l'objet ne fait rien de particulier (à part être dans l'inventaire, exemple: un corps, de la drogue, etc), celui-ci, une fois utilisé, disparaît sans laisser de traces... 

Est ce voulu ou est ce bel et bien un bug ?

**Comment by DayField** [comment]
On va mettre un système de "canUse" normalement :)

**Comment by rvwarrior** [comment]
ok c'était juste pour prévenir 👍
