### ISSUE TITLE
Fatal : trop de connexion

### ISSUE THREAD

**Issue by nmaroine** [ldlac/La_LifeRP#63]
![image](https://cloud.githubusercontent.com/assets/17453646/26764497/1ce28c7a-4968-11e7-9147-a3b3db0617aa.png)

Bonjour , voici mon problème. des fois plus personne n'arrive a se connecté (je suis avec la version du serveur de base, je tourne sur windows serveur 2012 R2).
merci d'avance.

**Comment by ldlac** [comment]
Étrange en principe si tu es à jour sur Master, le bug "devrait" être réglé

**Comment by nmaroine** [comment]
oui complètement à jour ...
en tous cas merci pour le travail fourni et bonne continuation Draziak

**Comment by ldlac** [comment]
Ok si le problème revient, dit le moi parce qu'en principe, il est réglé
