### ISSUE TITLE
Probleme "Ambulancier #56" Closed

### ISSUE THREAD

**Issue by MagnanQC** [ldlac/La_LifeRP#64]
Salut, 

je ne peux pas re-ouvrir le probleme. Je croit que je suis pas le seul qui as ce bug.

Merci, desole pour le le re-up.

**Comment by MagnanQC** [comment]
![image](https://cloud.githubusercontent.com/assets/28740577/26766374/9c91a640-495e-11e7-9f31-23a83575bcdd.png)

Je suis en service comme policier, et lorsque je suis coma, et aucune notification me donner l'option du "E", seulement que le "X".

Toutefois, meme si j'appuie sur "E", sa me spawn devant l'hopital. Or, lorsque je suis apparue, la notification a gauche du fameux "E" pour appeller l'ambulance apparais, et lorsque j'appuie dessu, les ambulancier ne recoivent pas l'apelle.

jai double verifier si l'ambulancier etais en service et "in-game" il l'étais.

Je verifie dans la base de donné, le joueur a bel et bien le ID 14 dans job, mais la colone du "enservice" est a 0.

Je roule sur "Master" branch

**Comment by ldlac** [comment]
J'ai push un fix récemment. Je test encore le truc. Par contre l'ID ambulancier est 13. Il est présentement "Hardcodé" dans les fichiers, éventuellement je vais le get de la bdd

**Comment by buddyqc** [comment]
Tu nutilise pas a 100% mysql idlac?

**Comment by ldlac** [comment]
Oui à 100% pour ?
