### ISSUE TITLE
Supprimer les PNJ Policier

### ISSUE THREAD

**Issue by Draxprodd** [ldlac/La_LifeRP#68]
Hello !

j'ai une petite question, comptez-vous supprimer les PNJ Policiers ? C'est très gênant, surtout quand ils patrouillent en véhicules, étant donné qu'ils sont innofensif les joueurs peuvent très bien voler un véhicule pour avoir un fusil à pompe, ou même tuer le policier pour prendre son arme..

Pas top ! :)

Merci à vous

**Comment by ldlac** [comment]
En effet, je cherche un moyen intéressant de le faire, si tu connais fait moi signe.

**Comment by Draxprodd** [comment]
https://forum.fivem.net/t/release-model-blacklist-v1-1/7574
https://forum.fivem.net/t/remove-all-npc-cop-and-military-from-server/17821/6

**Comment by PichotM** [comment]
le getclosestped ne fonctionne pas, mais il existe la fonction ClearAreaOfCops (jamais testée)

**Comment by ldlac** [comment]
Ouais j'ai déjà vu le ClearAreaOfCops mais ça delete même les véhicules de police des joueurs (je pense)

**Comment by Zouhh** [comment]
J'avais testé sur mon serveur ClearAreaOfCops et ça n'avait aucun effet...
Par contre, il faudrait tester ça : https://forum.fivem.net/t/release-disable-all-emergency-service-and-military-dispatching/23823

**Comment by PichotM** [comment]
la native fonctionne bien

**Comment by WalterWhite84** [comment]
@ldlac  tiens tu le met en (ex : neverpolice.lua dans client_base) et cela fonctionne tres tres bien depuis plusieurs jours sur mon serveur ....

https://www.mediafire.com/?aytaar38gno16aw

**Comment by ldlac** [comment]
Ajouté, en test
