### ISSUE TITLE
HUD Argent

### ISSUE THREAD

**Issue by Draxprodd** [ldlac/La_LifeRP#69]
Bonjour,

Petit soucis avec le HUD de l'argent sale et du liquide, il n'est plus là, je ne sais pas si c'est volontaire ou non...

Il y a également un soucis avec la banque, impossible de voir son solde (il ne s'update / affiche pas)

**Comment by FeaReDGlock** [comment]
En faite, il serait possible de savoir ou modifier afin que l'HUD reste afficher en haut a droite, selon le choix de la personne. C'est a dire si l'ont veut l'afficher ou pas 👍

**Comment by Draxprodd** [comment]
Après vérification avec mes yeux d'aveugle, il semblerait que le HUD s'affiche quand l'on fait F7 :)

**Comment by ldlac** [comment]
Oui, pour rendre le plus moins rempli, l'idée m'est venue et après consultation avec plusieurs personnes ça semble être une solution intéressante! Je vais tout de même vous mettre la possibilité de le laisser actif en permanence.
