### ISSUE TITLE
Possibilité d'ajouter armes policier.

### ISSUE THREAD

**Issue by FeaReDGlock** [ldlac/La_LifeRP#71]
Voila j'ai essayer d'ajouter des armes a l'armurerie mais elle apparaissent pas dans la liste donc je suppose qu'il y a surement un autre endroit ou il faut les ajouter ? Mais je sais pas lequel !

Aussi, l'affichage du compte en banque ne marche pas, aucun problème. Dans le menu du distributeur il y a écrit votre compte : 

En faite après c'est vide. Une idée pour sa ?

**Comment by Draxprodd** [comment]
fivemmenu_client.lua ligne 937 à 941 tu ajoutes ton arme

par exemple moi la FlashLight
VMenu.AddFunc(menu, "Lampe Torche", "vmenu:getArmory", {"WEAPON_Flashlight"}, "Obtenir cette arme")

Ensuite tu vas dans le fichier client.lua qui se trouve dans le jobs-police et à la ligne 17 à 19 tu vas rajouter ceci

{name="Lampe torche", id="WEAPON_Flashlight"},

(laisse la virgule, c'est pas comme sur Arma3 ou il faut les virer ^^)

**Comment by FeaReDGlock** [comment]
Ok thx je vais essayer :)
