### ISSUE TITLE
Garage hélicoptère + avion

### ISSUE THREAD

**Issue by Draxprodd** [ldlac/La_LifeRP#77]
Bonjour :)

J'ai remarqué que quand on sort un hélicoptère de la LSPD, on ne peux pas le ranger, sauf en allant le ranger à l'endroit pour les véhicules.

Egalement, les shops avions ne fonctionne pas (logo avion)

**Comment by ldlac** [comment]
Bon point, il n'y a pas de garage hélico pour l'instant,
Les blips avions sont que des aéroports.
