### ISSUE TITLE
Garage police

### ISSUE THREAD

**Issue by RayZennn** [ldlac/La_LifeRP#79]
J'aimerais savoir comment modifier le garage de la police.

**Comment by rvwarrior** [comment]
C'est à dire, tu veux faire quoi ?

**Comment by RayZennn** [comment]
Modifier des véhicules

**Comment by rvwarrior** [comment]
genre changer les véhicules qu'on te donne ? ou le menu direct ? 

sinon regarde dans fivemenu_client.lua

**Comment by ldlac** [comment]
Répondu plus haut, merci @rvwarrior
