### ISSUE TITLE
Trigger introuvable O_o

### ISSUE THREAD

**Issue by RyUkApples** [ldlac/La_LifeRP#8]
Coucou pourrais-je savoir dans quel fichiers est l'event TriggerClientEvent("mine:getJobs", source, user:getJob()) car je ne le trouve pas j'ai chercher dans le job mine mais rien pas de partie serveur

**Comment by RyUkApples** [comment]
J'suis con c'est du client putain "TriggerClientEvent" Putain srx kill me

**Comment by ldlac** [comment]
xD Tu as trouvé?

**Comment by RyUkApples** [comment]
Ouep :p 

Aussi j'aurais une question ^^

Aller vous faire des braquages (pas les es_robberies de Fivem si possible ils sont buggé..) ca rendrait le RP intéressant.

**Comment by ldlac** [comment]
Ouais c'est prévu. On va le faire from scratch surement étant que comme tu dis ce qui est dispo est plus ou moins fonctionnel!
