### ISSUE TITLE
Compte en banque n'apparait pas

### ISSUE THREAD

**Issue by FeaReDGlock** [ldlac/La_LifeRP#80]
http://prntscr.com/fgbq3k

C'est bizzare, il n'est pas affiché, meme avec F7, le compte en banque ne s'affiche pas du tout, mais pourtant je peux retirer de l'argent en deposer etc...

**Comment by sim2511** [comment]
C'est peut être volontaire, pareil pour le nom du métier, il n’apparaît pas non plus

**Comment by DayField** [comment]
Le compte en banque c est volontaire, les métiers c est parce que c est pas mis (ils sont dans le menu f7)

**Comment by FeaReDGlock** [comment]
Ok comment faire pour pouvoir le revoir et s'avoir combien on a ? Car perso je préfère l'affichage en haut a droite constant :)

**Comment by ldlac** [comment]
Devrait être fix avec ce patch. À me confirmer :)

**Comment by ldlac** [comment]
Et je parle directement à la banque, pas dans le hud

**Comment by iZykoS** [comment]
Mais du coup comment est ce que l'on fait pour afficher l'argent en banque dans le hud ?

**Comment by MRLEGENDS03** [comment]
problème fix l'argent apparaît de nouveau à la banque

**Comment by Gaston-Tricard** [comment]
Problème non réglé, l'affichage du HUD, n'est pas valable tout le temps.

**Comment by MRLEGENDS03** [comment]
sur mon serveur depuis la dernière maj, j'ai l'argent afficher à la banque est nous somme 5 players sur le serveur tourne en continue depuis plus de 24h sans problème de banque
