### ISSUE TITLE
Probleme MAJ [Jail System, Distributeur, Bugfix] pour Linux

### ISSUE THREAD

**Issue by RyUkApples** [ldlac/La_LifeRP#81]
Yo, je préviens que la nouvelle MAJ ne fonctionne pas sur Linux depuis la modif des CitizenMP.Server.exe.config et CitizenMP.Server.exe une erreur apparait en parlant de ces fichiers..

**Comment by RyUkApples** [comment]
J'ai pris un screen de l'erreur: http://prntscr.com/fgco59

**Comment by RyUkApples** [comment]
J'ai remis les deux anciens fichiers et ça refonctionne mais je laisse le ticket ouvert au cas ou vous proposeriez un patch ^^

**Comment by ldlac** [comment]
Étrange, je crois que c'est la version de mono qui a changé non? Pour le nouveau patch server fivem

**Comment by RyUkApples** [comment]
Quel nouveau patch je l'ai pas vu sur FiveM O_o, mais sinon pour Mono je sais pas j'utilise celle d'avant la version finale, car la version finale (5.0) est bugé sous Linux

**Comment by ldlac** [comment]
Le FiveM Server a été mise à jour il y a longtemps et les fichiers que j'avais mis dans le repo n'était plus à jour en fait

**Comment by RyUkApples** [comment]
Bhé j'ai bien la derniere MAJ étant donné que mon cfx date d'il y a 3 jours même pas, donc je ne sais pas vraiment :/

PS: Moyen que tu mette a jour la source du Wrapper ^^ ? Et aussi de check tes MP Discord stp je t'ai envoyé des trucs

**Comment by ldlac** [comment]
Ouais j'avoue pour les sources du Wrapper
