### ISSUE TITLE
Métier Fossoyeur

### ISSUE THREAD

**Issue by iSlyDz** [ldlac/La_LifeRP#86]
Bonjour, 
je viens vers vous pour vous informer que le métiers Fossoyeur est bugué.

Une fois la tenue changé et la voiture prise au cimetière, on nous donne aucune destination. donc on ne peut, rien faire avec ce metier.

On la testé 2 fois sans succés.

**Comment by FeaReDGlock** [comment]
Pareil pour la morgue on a pas de destination ou autre, on sait pas ce qu'on a a faire !

**Comment by mic75013** [comment]
Morgue > cimetiere...Cimetiere morg

Prendre le metier, aller au cimetiere, prendre un corp, retourner DANS la morgue( au sous sol ), deposer le corp. Pour le metier de fossoyeur, il faut des corps a la morgue

**Comment by FeaReDGlock** [comment]
Ouais mais c'est pas dit ce qu'il faut faire quand on prend le métier du coup, on est perdu, et pour les nouveaux qui prennent le job, ba la c'est la panade !

**Comment by sim2511** [comment]
Il m'a l'air compliqué ce métier effectivement ^_^

**Comment by ShakirDarwish** [comment]
Maintenant 100% fonctionel
