### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#87]
Bonjour,
j'ai installer le serveur, lié la base de donnée avec wamp en local et lancer le run sans rien toucher à autre choses, donc je lance five m rejoins le serveur en local (128.0.0.1) et le chargement est infini je spawn pas 
voici le screen des logs:
https://image.noelshack.com/fichiers/2017/23/1496830909-sans-titre.png

**Comment by FreakyMan82** [comment]
Salut !
T'as débloqué les fichiers dans 'resources\mysql-async\lib' ? (clic droite sur chaque fichier et débloquer)
Ip: 127.0.0.1...
Configure le config.lua "resources\mysql-async\lib" ? Essaye ...

**Comment by Julian51100** [comment]
d'accord j'essaye apres et j'te dis quoi

**Comment by Julian51100** [comment]
quand je fais clic deoit ya pas debloquer

**Comment by Julian51100** [comment]
et le fichier config est bien configurer

**Comment by Julian51100** [comment]
oui c'est 127.0.0.1 plutot j'me suis tromper

**Comment by Julian51100** [comment]
j'ai essayer avec d'autre source et sa marche ...

**Comment by Julian51100** [comment]
qui peux m'aider :(

**Comment by Julian51100** [comment]
je pense que c'est bon merci de l'aider ;)

**Comment by Julian51100** [comment]
je pense que c'est bon merci de l'aider ;)

**Comment by XNakon** [comment]
Comment tu a régler ton problème j'ai le même problème

**Comment by Julian51100** [comment]
mes fichier config etais mal liee a la db

**Comment by XNakon** [comment]
Ok merci
