### ISSUE TITLE
problème de db

### ISSUE THREAD

**Issue by XNakon** [ldlac/La_LifeRP#90]
J'ai un problème avec la DB elle est bien installé et les deux fichiers config dans mysql-async/bin son ok.mais il y a plein d'erreurs quand je lance le serveur?? Quelqu'un a une idée du problème svp

**Comment by MagnanQC** [comment]
c'est quoi les erreur qui t'affiche ?

**Comment by XNakon** [comment]
http://imgur.com/McgJCI3

**Comment by XNakon** [comment]
Le problème vien d'un fichier dans la mysql-async/lib et pourtant j'ai changé les mots et user

Je suis une machine virtuelle OVH Windows serveur 2012 

Merci de votre aide

**Comment by XNakon** [comment]
Tout fonctionnait avec l'ancienne version master

**Comment by Gaston-Tricard** [comment]
Débloque les dll du dossier mysql

**Comment by XNakon** [comment]
super !!!! tout fonctionne mille merci!!!!! :)
