### ISSUE TITLE
Comment ouvrir la Liste des joueur + ID ?! (Z)

### ISSUE THREAD

**Issue by SirSmog1** [ldlac/La_LifeRP#94]
Bonjours

je n'arrive pas a ouvrir la liste des joueurs pour voir les IDs (Z)
Et
serait ils possible que cette fonctions sois disponible que pour les admins ?!

Merci a vous

**Comment by smixiop** [comment]
flèche haute

**Comment by sim2511** [comment]
Même problème

**Comment by SirSmog1** [comment]
fleche haut ou Z ne fonctionne pas ....

**Comment by SirSmog1** [comment]
ha trouver .... lol yavais un delait rajouter sur la touche --'
problème régler x)

**Comment by Julian51100** [comment]
j'y arrive pas :(
