### ISSUE TITLE
probleme (on ce ne voit pas entre joueurs sur la map

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#95]
bonjour, 
j'ai installer le serveur aujourd'hui et quand on est plusieur sur le serveur bah on ce voit plus malgre qu'on est nous deux au commissariat hors que a la connection on ce voyait et aussi le deuxieme problème quand on ce co pour la première fois on a 2000$ et la rien enfait on ce co on a 0$ sur le serveur hors que sur le base de donnée on a 2000$ 
besoin d'aide

**Comment by Julian51100** [comment]
on voit pas l'argent qu'on a dans le menu pause

**Comment by Julian51100** [comment]
j'ai le meme probleme que sa : 
https://github.com/ldlac/La_LifeRP/issues/30

**Comment by IRemake** [comment]
Est ce que tu peux nous faire des screens ?

**Comment by Julian51100** [comment]
Pour l'argent enfaite sa marche fait juste apouiyer sur f7 mais j'aimerais que l'argznt s'affiche dans le menu pause 

et comme j'ai dis genre on ce co avec des potes et au bout de genre 5 min sayer j'les vois plus apres on a essayer de deco reco et tout et tjrs pareil au bout de genre 5 min j'les vois plus

**Comment by DayField** [comment]
l argent du menu pause ne s affiche puisque ça n as rien à voir avec le mode Rp, c est l argent gta Online/solo

**Comment by Julian51100** [comment]
d'accord et pour l'autre probleme ?

**Comment by Julian51100** [comment]
comme j'ai dis genre on ce co avec des potes et au bout de genre 5 min sayer j'les vois plus apres on a essayer de deco reco et tout et tjrs pareil au bout de genre 5 min j'les vois plus

**Comment by Julian51100** [comment]
PROBLEME RESOLU !
