### ISSUE TITLE
HUD Argent Clignote

### ISSUE THREAD

**Issue by iZykoS** [ldlac/La_LifeRP#96]
L'HUD de l'argent sur mon serveur et les écritures en haut a droite clignote et donne des crises d'épilepsie

**Comment by MagnanQC** [comment]
Moi il faut que jappuit sur F7 pour le faire apparaitre (et en meme temps que le menu !!)
Lorsque je ferme le menu, le HUD seteint !

Prendre note que je suis sur la MASTER derniere version.

**Comment by FeaReDGlock** [comment]
Peut etre fix dans la derniere version ? Des nouvelles iZykoS ?

**Comment by iZykoS** [comment]
Alors absolument pas désoler je passe mon bac, je m'occupe plus trop de finir mon serveur :/ je te tiendrai au courant une fois mes épreuves terminer ;)

**Comment by ldlac** [comment]
HUD désormais visible en permanence :)!
