### ISSUE TITLE
Probleme de disparition de joueurs au bout de 5 minutes

### ISSUE THREAD

**Issue by Julian51100** [ldlac/La_LifeRP#98]
bonjour, 
je contact le support en ce jour car j'ai un soucis sur mon serveur enfait c'est simple je me connecte avec d'autre joueur et au bout de 5 min environ pouf pu personne hors qu'il sont co pourtant ... 
voici ma machine de dev : https://www.firstheberg.com/fr/vps-kvm-stockage

cordialement,
julian.f

**Comment by MagnanQC** [comment]
sa m'est deja arriver dans la passer, mais jutilisais un autre script autre que La_Life, jai tout simplement redemarrer le serveur, et jamais que cest encore arriver.

Peut etre le core du serveur FiveM .. 

Je ne donne que mon avis !

**Comment by Julian51100** [comment]
ouais sa doit etre un bug surement

**Comment by Julian51100** [comment]
j'ai une machine avec 4 go de ram et 200 mbps dans ca va large j'trouve

**Comment by Julian51100** [comment]
mais genre enfaite il monte dans ma voiture que j'ai voler et la ya un petit freeze et boom j'le vois plus

**Comment by misterdark441** [comment]
j'ai le même problème au bout d'un moment je le voie plus mais quand il se déco pour se reconnecter je voie le message de déco

**Comment by Julian51100** [comment]
c'est trop chelou :o

**Comment by misterdark441** [comment]
je sais pas si sa vient du serveur ou du vps ou de la co de mon pote

**Comment by Julian51100** [comment]
je pense que sa vien du serveur car j'ai un vps avec 4 go de ram et 200 mbps

**Comment by misterdark441** [comment]
la même

**Comment by Julian51100** [comment]
quelqu'un peut nous aidez ?

**Comment by misterdark441** [comment]
j'avoue sa serais pas de refus

**Comment by Julian51100** [comment]
t'es chez quel hebergeur

**Comment by misterdark441** [comment]
firstheberg

**Comment by Julian51100** [comment]
moi aussi bizzarement :o

**Comment by Julian51100** [comment]
si sa ce trouve il surcharge leurs machine de vps -_-

**Comment by Julian51100** [comment]
VOUS AVEZ QUOI COMME MACHINE QUI HEBERG LE SERVEUR

**Comment by MagnanQC** [comment]
J'ai personnellement un VPS KVM que n'héberge moi même avec 4go ram 6 core.

Cette machine sert à développer et tester, tandis que nous allons optez pour un dédier pour la production.

**Comment by Julian51100** [comment]
j'ai un 4 go de ram et 24 core

**Comment by SxProject** [comment]
bonjour Julian j'avais le même problème sur cette hébergeur je suis passer chez OVH sur un serveur linux et depuis tout va bien.

**Comment by Julian51100** [comment]
je vais passer chez ovh mais sur du windows ;)

**Comment by Julian51100** [comment]
ta pris quoi c'est ovh ? 
merci de ta reponse l'amis ;)

**Comment by SxProject** [comment]
oui chez OVH un VPS mais sous linux

**Comment by Julian51100** [comment]
quel vps ?

**Comment by Julian51100** [comment]
ta pris quel vps et je pense prendre un vps mais sous windows c'est mieux

**Comment by SxProject** [comment]
https://www.ovh.com/fr/vps/vps-ssd.xml
le VPS SSD 3 mais je ne sais pas si il font sous windows

**Comment by Julian51100** [comment]
pourquoi ssd et pas un cloud ?

**Comment by SxProject** [comment]
il est pas très chère en ssd et c largement suffisant pour se style de serveur

**Comment by Julian51100** [comment]
d'accord merci de ton avis, j'crois pas qu'il fond sur windows

**Comment by SxProject** [comment]
De rien

**Comment by Julian51100** [comment]
ya pas avec windows je crois

**Comment by Julian51100** [comment]
PROBLEME RESOLU !

**Comment by Julian51100** [comment]
Je réouvre cette issue, je suis passé chez OVH et toujours le même problème

**Comment by ldlac** [comment]
Deux issues ouvertes sur le même sujet
